global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#ilya_ivanov'
