---
- name: Run docker container
  hosts: all
  become: true
  tasks:

    - name: run container
      docker_container:
        name: reddit-app
        image: ilya8008/otus-reddit:1.0
        detach: yes
        network_mode: host
        ports:
          - "9292:9292"
        state: started
